name: Publish articles

on:
  push:
    branches:
      - main # ※デフォルトブランチがmasterの場合は master に書き換えてください
  workflow_dispatch:

permissions:
  contents: write # 最後にGitへプッシュするために必須の設定です

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install qiita-cli
        run: npm install -g @qiita/qiita-cli

      - name: Publish articles
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
        run: qiita publish --all

      - name: Commit and push diff
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add public/*
          if ! git diff --staged --exit-code --quiet; then
            git commit -m "Updated by qiita-cli"
            git push
          fi
